# Generated by Django 5.1.6 on 2025-02-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('min_players', models.PositiveIntegerField()),
                ('max_players', models.PositiveIntegerField()),
                ('min_duration', models.PositiveIntegerField()),
                ('max_duration', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='boardgames.game')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveBigIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='boardgames.history')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='boardgames.player')),
            ],
        ),
    ]
