# Generated by Django 5.1.6 on 2025-02-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_category_game_categories_expansion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='memo',
            new_name='description',
        ),
    ]
