# Generated by Django 5.1.6 on 2025-02-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_rename_categories_game_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'histories'},
        ),
    ]
