# Generated by Django 5.1.6 on 2025-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_alter_category_options_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
