# Generated by Django 5.1.6 on 2025-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='duration',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
