# Generated by Django 5.1.6 on 2025-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0014_alter_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'mechanisms',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanism',
            field=models.ManyToManyField(blank=True, to='boardgames.mechanism'),
        ),
    ]
