# Generated by Django 5.1.6 on 2025-03-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0015_mechanism_alter_category_options_game_summary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mechanism',
            new_name='Mechanic',
        ),
        migrations.AlterModelOptions(
            name='mechanic',
            options={'ordering': ['name'], 'verbose_name_plural': 'mechanics'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='mechanism',
            new_name='mechanic',
        ),
    ]
