# Generated by Django 5.1.6 on 2025-03-16 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0016_rename_mechanism_mechanic_alter_mechanic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-play_date', '-play_time'], 'verbose_name_plural': 'histories'},
        ),
        migrations.AddField(
            model_name='history',
            name='play_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
